const app = document.getElementById("app");
const div = document.createElement("div")
    div.innerHTML = `
    <table>
		<tr>
			<th>ID</th>
			<th>A</th>
			<th>B</th>
			<th>C</th>
			<th>D</th>
			<th>E</th>
			<th>F</th>
			<th>G</th>
			<th>H</th>
			<th>I</th>
			<th>J</th>
		</tr>
		<tr>
			<td>1</td>
			<td>A1-FqM=</td>
			<td>B1-W5U=</td>
			<td>C1-q4Y=</td>
			<td>D1-M6E=</td>
			<td>E1-IiQ=</td>
			<td>F1-3q4=</td>
			<td>G1-e3c=</td>
			<td>H1-i/c=</td>
			<td>I1-woE=</td>
			<td>J1-ST0=</td>
		</tr>
		<tr>
			<td>2</td>
			<td>A1-FqM=</td>
			<td>B1-W5U=</td>
			<td>C1-q4Y=</td>
			<td>D1-M6E=</td>
			<td>E1-IiQ=</td>
			<td>F1-3q4=</td>
			<td>G1-e3c=</td>
			<td>H1-i/c=</td>
			<td>I1-woE=</td>
			<td>J1-ST0=</td>
		</tr>
		<tr>
			<td>3</td>
			<td>A1-FqM=</td>
			<td>B1-W5U=</td>
			<td>C1-q4Y=</td>
			<td>D1-M6E=</td>
			<td>E1-IiQ=</td>
			<td>F1-3q4=</td>
			<td>G1-e3c=</td>
			<td>H1-i/c=</td>
			<td>I1-woE=</td>
			<td>J1-ST0=</td>
		</tr>
		<tr>
			<td>4</td>
			<td>A1-FqM=</td>
			<td>B1-W5U=</td>
			<td>C1-q4Y=</td>
			<td>D1-M6E=</td>
			<td>E1-IiQ=</td>
			<td>F1-3q4=</td>
			<td>G1-e3c=</td>
			<td>H1-i/c=</td>
			<td>I1-woE=</td>
			<td>J1-ST0=</td>
		</tr>
		<tr>
			<td>5</td>
			<td>A1-FqM=</td>
			<td>B1-W5U=</td>
			<td>C1-q4Y=</td>
			<td>D1-M6E=</td>
			<td>E1-IiQ=</td>
			<td>F1-3q4=</td>
			<td>G1-e3c=</td>
			<td>H1-i/c=</td>
			<td>I1-woE=</td>
			<td>J1-ST0=</td>
		</tr>
		<tr>
			<td>6</td>
			<td>A1-FqM=</td>
			<td>B1-W5U=</td>
			<td>C1-q4Y=</td>
			<td>D1-M6E=</td>
			<td>E1-IiQ=</td>
			<td>F1-3q4=</td>
			<td>G1-e3c=</td>
			<td>H1-i/c=</td>
			<td>I1-woE=</td>
			<td>J1-ST0=</td>
		</tr>
	</table>`
app?.appendChild(div);
